version: '3'
services:
    templates:
        container_name: templates
        depends_on: 
            - postgres-db
        build: 
            context: ./
            dockerfile: templates/Dockerfile
        environment:
            - PORT=8080
        ports:
            - 8080:8080
    checkups:
        container_name: checkups
        depends_on: 
            - postgres-db
        build: 
            context: ./
            dockerfile: checkups/Dockerfile
        environment:
            - PORT=8081
        ports:
            - 8081:8081
    users:
        container_name: users
        depends_on: 
            - postgres-db
        build: 
            context: ./
            dockerfile: users/Dockerfile
        environment:
            - PORT=8082
        ports:
            - 8082:8082
    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        ports: 
            - 5432:5432
