version: '3'
services:
    utilities:
        depends_on: 
            - postgres
        build: 
            context: ./
            dockerfile: utilities/Dockerfile
        environment:
            - PORT=8080
        ports:
            - 8080:8080
    checkups:
        depends_on: 
            - postgres
        build: 
            context: ./
            dockerfile: checkups/Dockerfile
        environment:
            - PORT=8081
        ports:
            - 8081:8081
    users:
        depends_on: 
            - postgres
        build: 
            context: ./
            dockerfile: users/Dockerfile
        volumes:
          - ${CREDENTIALS_PATH}:/credentials.json
        environment:
            - PORT=8082
            - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
            - PROJECT_ID=${PROJECT_ID}
        ports:
            - 8082:8082
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        ports: 
            - 5432:5432
